# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fc7c53e0b61f9a9a49134f0e077b39eb04ad0a9cd20828bccd5bb5e3cad092e9e86b7183ec5a888f0e3d5fcd72924a09c701ab11a520d4ecf1ae6e86fc30959

test:
  secret_key_base: e1985168883b19db84448d2c31838913345826f95a99867a0dd4c8edad29503207104d700eecdfd64c4cd3c4792b3c3abb1b833700030783542539e1bc2993d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
